import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f1fbfe",
        "surface-dim": "#d2dcdf",
        "surface-bright": "#f1fbfe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ebf5f9",
        "surface-container": "#e5f0f3",
        "surface-container-high": "#e0eaed",
        "surface-container-highest": "#dae4e7",
        "on-surface": "#141d20",
        "on-surface-variant": "#434848",
        "inverse-surface": "#283235",
        "inverse-on-surface": "#e8f2f6",
        outline: "#737878",
        "outline-variant": "#c3c7c8",
        "surface-tint": "#586061",
        primary: "#182021",
        "on-primary": "#ffffff",
        "primary-container": "#2d3536",
        "on-primary-container": "#959d9e",
        "inverse-primary": "#c0c8c9",
        secondary: "#506357",
        "on-secondary": "#ffffff",
        "secondary-container": "#d3e8d9",
        "on-secondary-container": "#56695d",
        tertiary: "#142216",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#29372a",
        "on-tertiary-container": "#90a08f",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dce4e5",
        "primary-fixed-dim": "#c0c8c9",
        "on-primary-fixed": "#151d1e",
        "on-primary-fixed-variant": "#404849",
        "secondary-fixed": "#d3e8d9",
        "secondary-fixed-dim": "#b7cbbe",
        "on-secondary-fixed": "#0e1f16",
        "on-secondary-fixed-variant": "#394b40",
        "tertiary-fixed": "#d6e7d4",
        "tertiary-fixed-dim": "#bbcbb9",
        "on-tertiary-fixed": "#111f13",
        "on-tertiary-fixed-variant": "#3c4a3d",
        background: "#f1fbfe",
        "on-background": "#141d20",
        "surface-variant": "#dae4e7",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        mono: ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        caption: ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        caption: ["12px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0", fontWeight: "400" }],
        display: ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "700" }],
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "max-content-width": "1280px",
        "reading-column-width": "720px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
